# Generated by Django 2.1.1 on 2018-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('sourse', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('ptime', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
