# Generated by Django 2.1.1 on 2018-09-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.TextField()),
                ('m_email', models.CharField(max_length=50)),
                ('m_address', models.CharField(max_length=50)),
                ('m_message', models.TextField()),
            ],
        ),
    ]
