# Generated by Django 2.1.1 on 2018-09-26 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.IntegerField(choices=[(1, '阶段1'), (2, '阶段1'), (3, '阶段2'), (5, '阶段1'), (7, '阶段3'), (8, '阶段2'), (9, '阶段3'), (10, '阶段4')], default=0, verbose_name='阶段id')),
                ('number', models.IntegerField(default=0, null=True)),
                ('title', models.CharField(max_length=255, null=True, verbose_name='标题')),
                ('days', models.IntegerField(default=0, null=True, verbose_name='学时')),
                ('advancing', models.CharField(max_length=255, null=True, verbose_name='高级内容')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='状态')),
                ('creator', models.CharField(max_length=100, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 20, 36, 420339), verbose_name='创建时间')),
                ('updater', models.CharField(max_length=100, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 20, 36, 420339), verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '一级大纲',
                'db_table': 'outline',
            },
        ),
    ]
