# Generated by Django 2.1.1 on 2018-09-26 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 24, 57, 132745), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 24, 57, 132745), verbose_name='更新时间'),
        ),
    ]
