# Generated by Django 2.1.1 on 2018-09-27 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0004_auto_20180926_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlinemodel',
            name='stage_id',
        ),
        migrations.AddField(
            model_name='outlinemodel',
            name='version',
            field=models.IntegerField(default=0, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 45, 58, 803718), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 45, 58, 803718), verbose_name='更新时间'),
        ),
    ]
