# Generated by Django 2.1.1 on 2018-09-27 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0005_auto_20180927_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinemodel',
            name='stage_id',
            field=models.IntegerField(default=0, verbose_name='阶段id'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 50, 9, 499933), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 50, 9, 499933), verbose_name='更新时间'),
        ),
    ]
