# Generated by Django 2.1.1 on 2018-09-27 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0007_auto_20180927_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 52, 31, 477080), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 52, 31, 477080), verbose_name='更新时间'),
        ),
    ]
