# Generated by Django 2.1.1 on 2018-09-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Four',
            fields=[
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.Three')),
                ('des', models.TextField()),
                ('font', models.TextField()),
            ],
        ),
    ]
