# Generated by Django 2.1.1 on 2018-09-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=50)),
                ('gtype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.AddField(
            model_name='games',
            name='bind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.People'),
        ),
    ]
