# Generated by Django 2.1.1 on 2018-09-26 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(choices=[(1, 'IOS'), (2, 'VR'), (3, 'VR'), (7, 'zy'), (11, 'zy'), (12, 'efaefaef')], default=0, verbose_name='学科编号')),
                ('title', models.CharField(max_length=50, verbose_name='阶段')),
                ('number', models.IntegerField(default=0, null=True, verbose_name='排序')),
                ('days', models.IntegerField()),
                ('project', models.CharField(max_length=255, verbose_name='项目')),
                ('teaching', models.CharField(max_length=255, verbose_name='教学方法')),
                ('learning', models.CharField(max_length=255, verbose_name='学习方法')),
                ('sharing', models.CharField(max_length=255, verbose_name='学生分享')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='状态')),
                ('creator', models.CharField(max_length=100, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 14, 10, 545126), verbose_name='创建时间')),
                ('updater', models.CharField(max_length=100, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 14, 10, 545126), verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '阶段',
            },
        ),
    ]
