# Generated by Django 2.1.1 on 2018-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='version',
            field=models.IntegerField(default=0, verbose_name='版本'),
        ),
    ]
