# Generated by Django 2.1.1 on 2018-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('paddress', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Publisher',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='bid',
            field=models.ManyToManyField(to='myApp.Publisher'),
        ),
    ]
