# Generated by Django 2.1.1 on 2018-10-10 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20181009_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='人气指数'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 9, 30, 3, 942385), verbose_name='创建时间'),
        ),
    ]
