# Generated by Django 2.1.1 on 2018-09-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectGoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=30, verbose_name='收件人')),
                ('detail_address', models.CharField(max_length=200, null=True, verbose_name='详细地址')),
                ('postcode', models.IntegerField(default=0, verbose_name='邮政编码')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='联系方式')),
                ('is_used', models.BooleanField(verbose_name='是否正在使用')),
            ],
            options={
                'verbose_name_plural': '收货信息管理',
                'db_table': 'CollectGoods',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='收货地址')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='collectgoodsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel'),
        ),
    ]
