# Generated by Django 2.1.1 on 2018-09-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject_id', models.IntegerField(null=True)),
                ('days', models.IntegerField()),
                ('number', models.IntegerField(null=True)),
                ('project', models.CharField(max_length=255, null=True)),
                ('teaching', models.CharField(max_length=255, null=True)),
                ('learning', models.CharField(max_length=255)),
                ('sharing', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
