# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInof',
            new_name='UserInfo',
        ),
    ]
