# Generated by Django 2.1.1 on 2018-09-20 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('days', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('assurance', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 9, 59, 34, 555708)),
        ),
    ]
