# Generated by Django 2.1.1 on 2018-09-25 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20180920_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 21, 13, 30, 177738)),
        ),
    ]
