# Generated by Django 2.1.1 on 2018-09-27 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(null=True)),
                ('days', models.IntegerField()),
                ('amount', models.CharField(max_length=100)),
                ('assurance', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
                ('creator', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 44, 51, 180231))),
                ('updater', models.CharField(max_length=100, null=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 44, 51, 180231))),
                ('version', models.IntegerField(default=0, verbose_name='版本')),
            ],
            options={
                'verbose_name_plural': '学科',
                'db_table': 'subject',
            },
        ),
    ]
