# Generated by Django 2.1.1 on 2018-09-27 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20180927_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 52, 31, 445831)),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 20, 52, 31, 445831)),
        ),
    ]
