# Generated by Django 2.1.1 on 2018-09-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100, null=True)),
                ('uage', models.IntegerField(null=True)),
                ('usex', models.NullBooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='First',
        ),
    ]
