# Generated by Django 2.1.1 on 2018-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=200)),
                ('bauthor', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('paddress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ManyToManyField(to='myApp.Publication'),
        ),
    ]
